name: track_mjx
channels:
  - conda-forge

dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - pandas
  - h5py
  - ffmpeg
  - ipykernel
  - jupyterlab
  - seaborn
  - scikit-learn
  - mesalib
  - pip
  - pip:
    - "--editable=.[with-cuda]"
