name: track_mjx
channels:
  - conda-forge
  # - menpo

dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pandas
  - h5py
  - ffmpeg
  - ipykernel
  - jupyterlab
  - pip
  - pip:
    - "--editable=.[with-cuda]"
