"""Inference result data structures for VQ-VAE analysis.

This module provides data structures for representing VQ-VAE inference results.
Rollout data is loaded from H5 files generated by the inference module.
"""

from dataclasses import dataclass
from typing import Any

import numpy as np


@dataclass
class InferenceResult:
    """Result from running VQ-VAE inference on a clip.

    Attributes:
        clip_idx: Index of the reference clip.
        code_indices: Primary (L0) code indices per frame, shape [T].
        qpos: Generalized positions per frame, shape [T, nq].
        qvel: Generalized velocities per frame, shape [T, nv].
        rewards: Reward values per frame, shape [T].
        states: Optional list of environment states for rendering.
        rvq_indices: Optional per-depth code indices, tuple of D arrays each [T].
            rvq_indices[0] == code_indices for consistency.
        reward_components: Optional per-term reward breakdown. Maps reward term
            name (e.g. ``"root_pos"``) to per-frame values, shape [T].
    """

    clip_idx: int
    code_indices: np.ndarray
    qpos: np.ndarray
    qvel: np.ndarray
    rewards: np.ndarray
    states: list[Any] | None = None
    rvq_indices: tuple[np.ndarray, ...] | None = None
    reward_components: dict[str, np.ndarray] | None = None
