# Copyright 2024 The Brax Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Proximal policy optimization training.

See: https://arxiv.org/pdf/1707.06347.pdf
"""

from typing import Any, Callable, Tuple

from brax.training import types
from brax.training.agents.ppo import networks as ppo_networks
from brax.training.types import Params
import flax
import jax
import jax.numpy as jnp
import optax


@flax.struct.dataclass
class PPONetworkParams:
    """Contains training state for the learner."""

    policy: Params
    value: Params


def compute_gae(
    truncation: jnp.ndarray,
    termination: jnp.ndarray,
    rewards: jnp.ndarray,
    values: jnp.ndarray,
    bootstrap_value: jnp.ndarray,
    lambda_: float = 1.0,
    discount: float = 0.99,
):
    """Calculates the Generalized Advantage Estimation (GAE).

    Args:
      truncation: A float32 tensor of shape [T, B] with truncation signal.
      termination: A float32 tensor of shape [T, B] with termination signal.
      rewards: A float32 tensor of shape [T, B] containing rewards generated by
        following the behaviour policy.
      values: A float32 tensor of shape [T, B] with the value function estimates
        wrt. the target policy.
      bootstrap_value: A float32 of shape [B] with the value function estimate at
        time T.
      lambda_: Mix between 1-step (lambda_=0) and n-step (lambda_=1). Defaults to
        lambda_=1.
      discount: TD discount.

    Returns:
      A float32 tensor of shape [T, B]. Can be used as target to
        train a baseline (V(x_t) - vs_t)^2.
      A float32 tensor of shape [T, B] of advantages.
    """

    truncation_mask = 1 - truncation
    # Append bootstrapped value to get [v1, ..., v_t+1]
    values_t_plus_1 = jnp.concatenate(
        [values[1:], jnp.expand_dims(bootstrap_value, 0)], axis=0
    )
    deltas = rewards + discount * (1 - termination) * values_t_plus_1 - values
    deltas *= truncation_mask

    acc = jnp.zeros_like(bootstrap_value)
    vs_minus_v_xs = []

    def compute_vs_minus_v_xs(carry, target_t):
        lambda_, acc = carry
        truncation_mask, delta, termination = target_t
        acc = delta + discount * (1 - termination) * truncation_mask * lambda_ * acc
        return (lambda_, acc), (acc)

    (_, _), (vs_minus_v_xs) = jax.lax.scan(
        compute_vs_minus_v_xs,
        (lambda_, acc),
        (truncation_mask, deltas, termination),
        length=int(truncation_mask.shape[0]),
        reverse=True,
    )
    # Add V(x_s) to get v_s.
    vs = jnp.add(vs_minus_v_xs, values)

    vs_t_plus_1 = jnp.concatenate([vs[1:], jnp.expand_dims(bootstrap_value, 0)], axis=0)
    advantages = (
        rewards + discount * (1 - termination) * vs_t_plus_1 - values
    ) * truncation_mask
    return jax.lax.stop_gradient(vs), jax.lax.stop_gradient(advantages)


def compute_ppo_loss(
    params: PPONetworkParams,
    normalizer_params: Any,
    data: types.Transition,
    rng: jnp.ndarray,
    step: int,
    ppo_network: ppo_networks.PPONetworks,
    entropy_cost: float = 1e-4,
    encoder_kl_weight: float = 1e-3,
    prior_kl_weight: float = 1e-3,
    discounting: float = 0.9,
    reward_scaling: float = 1.0,
    gae_lambda: float = 0.95,
    clipping_epsilon: float = 0.3,
    normalize_advantage: bool = True,
    kl_schedule_encoder: Callable | None = None,
    kl_schedule_prior: Callable | None = None,
) -> Tuple[jnp.ndarray, types.Metrics]:
    """Computes PPO loss.

    Args:
      params: Network parameters,
      normalizer_params: Parameters of the normalizer.
      data: Transition that with leading dimension [B, T]. extra fields required
        are ['state_extras']['truncation'] ['policy_extras']['raw_action']
          ['policy_extras']['log_prob']
      rng: Random key
      ppo_network: PPO networks.
      entropy_cost: entropy cost.
      discounting: discounting,
      reward_scaling: reward multiplier.
      gae_lambda: General advantage estimation lambda.
      clipping_epsilon: Policy loss clipping epsilon
      normalize_advantage: whether to normalize advantage estimate

    Returns:
      A tuple (loss, metrics)
    """

    _, policy_key, entropy_key = jax.random.split(rng, 3)
    parametric_action_distribution = ppo_network.parametric_action_distribution
    policy_apply = ppo_network.policy_network.apply
    value_apply = ppo_network.value_network.apply

    # Put the time dimension first.
    data = jax.tree_util.tree_map(lambda x: jnp.swapaxes(x, 0, 1), data)
    policy_logits, latent_mean, latent_logvar, priornetwork_mean, priornetwork_logvar = policy_apply(
        normalizer_params, params.policy, data.observation, policy_key
    )

    baseline = value_apply(normalizer_params, params.value, data.observation)

    bootstrap_value = value_apply(
        normalizer_params, params.value, data.next_observation[-1]
    )

    rewards = data.reward * reward_scaling
    truncation = data.extras["state_extras"]["truncation"]
    termination = (1 - data.discount) * (1 - truncation)

    target_action_log_probs = parametric_action_distribution.log_prob(
        policy_logits, data.extras["policy_extras"]["raw_action"]
    )
    behaviour_action_log_probs = data.extras["policy_extras"]["log_prob"]

    vs, advantages = compute_gae(
        truncation=truncation,
        termination=termination,
        rewards=rewards,
        values=baseline,
        bootstrap_value=bootstrap_value,
        lambda_=gae_lambda,
        discount=discounting,
    )
    if normalize_advantage:
        advantages = (advantages - advantages.mean()) / (advantages.std() + 1e-8)
    rho_s = jnp.exp(target_action_log_probs - behaviour_action_log_probs)

    surrogate_loss1 = rho_s * advantages
    surrogate_loss2 = (
        jnp.clip(rho_s, 1 - clipping_epsilon, 1 + clipping_epsilon) * advantages
    )

    policy_loss = -jnp.mean(jnp.minimum(surrogate_loss1, surrogate_loss2))

    # Value function loss
    v_error = vs - baseline
    v_loss = jnp.mean(v_error * v_error) * 0.5 * 0.5

    # Entropy reward
    entropy = jnp.mean(
        parametric_action_distribution.entropy(policy_logits, entropy_key)
    )
    entropy_loss = entropy_cost * -entropy

    # KL Divergence for latent layer
    current_encoder_kl_weight = encoder_kl_weight
    current_prior_kl_weight = prior_kl_weight
    if kl_schedule_encoder is not None:
        scheduled_weight = kl_schedule_encoder(step)
        current_encoder_kl_weight = scheduled_weight
    if kl_schedule_prior is not None:
        scheduled_weight = kl_schedule_prior(step)
        current_prior_kl_weight = scheduled_weight

    # Temporal smoothness loss: MSE between consecutive latent means
    # Encourages smooth transitions in the latent space
    if latent_mean.shape[0] > 1:  # If we have more than one timestep
        # Get consecutive latent means
        z_prev = latent_mean[:-1]  # z_0, ..., z_{T-2}
        z_curr = latent_mean[1:]   # z_1, ..., z_{T-1}

        # MSE between consecutive latent means
        encoder_kl_loss_unweighted = jnp.mean(jnp.square(z_curr - z_prev))
        encoder_kl_loss = current_encoder_kl_weight * encoder_kl_loss_unweighted
    else:
        # Only one timestep, no temporal smoothness loss
        encoder_kl_loss_unweighted = jnp.array(0.0)
        encoder_kl_loss = jnp.array(0.0)

    var_ratio = jnp.exp(latent_logvar - priornetwork_logvar)  # σ_q^2 / σ_p^2
    mean_diff_sq = jnp.square(latent_mean - priornetwork_mean) / jnp.exp(priornetwork_logvar)  # (μ_q - μ_p)^2 / σ_p^2
    log_var_diff = priornetwork_logvar - latent_logvar  # log(σ_p^2) - log(σ_q^2)
    
    prior_kl_loss_unweighted = 0.5 * jnp.mean(var_ratio + mean_diff_sq - 1 + log_var_diff)
    prior_kl_loss = current_prior_kl_weight * prior_kl_loss_unweighted

    # Update total loss
    total_loss = policy_loss + v_loss + entropy_loss + encoder_kl_loss + prior_kl_loss  # NEW

    return total_loss, {
        "total_loss": total_loss,
        "policy_loss": policy_loss,
        "v_loss": v_loss,
        "entropy_loss": entropy_loss,
        "encoder_kl_loss": encoder_kl_loss_unweighted,
        "encoder_prior_kl_loss": prior_kl_loss_unweighted,
        "encoder_kl_weight": current_encoder_kl_weight,
        "encoder_prior_kl_weight": current_prior_kl_weight,
    }


def create_ramp_schedule(
    start_value: float = 0.0001,
    end_value: float = 0.1,
    ramp_steps: int = 1000,
    delay_steps: int = 0,
    schedule: str = "linear",
    period: int = 45,
) -> optax.Schedule:
    """
    Creates a schedule that can be either:
    - A linear ramp from start_value to end_value
    - A cyclic cosine schedule oscillating between start_value and end_value with given period
    - A cyclic sine schedule oscillating between start_value and end_value with given period
    
    Args:
        start_value: The starting value of the schedule.
        end_value: The ending value of the schedule. If end_value > start_value, ramps up.
            If end_value < start_value, ramps down (anneals).
        ramp_steps: Number of steps over which to ramp (for linear schedule).
        delay_steps: Number of steps to wait before ramping begins. During this period,
            the schedule returns the start_value.
        schedule: Type of schedule - "linear", "cosine", or "sine".
        period: Period for cyclic schedules (cosine/sine).
    """

    def schedule_fn(step):
        step = jnp.asarray(step, dtype=jnp.float32)

        if schedule == "linear":
            # Calculate progress after delay
            effective_step = step - delay_steps
            progress = jnp.clip(effective_step / ramp_steps, 0.0, 1.0)
            is_delayed = step < delay_steps
            ramped_value = start_value + progress * (end_value - start_value)
            return jnp.where(is_delayed, start_value, ramped_value)
        elif schedule == "cosine":  # cosine cyclic
            # Apply delay to cyclic schedules as well
            effective_step = jnp.maximum(step - delay_steps, 0.0)
            is_delayed = step < delay_steps
            # Convert step to angle in [0, 2π] based on period
            angle = (2 * jnp.pi * effective_step) / period
            # Scale and shift to oscillate between start_value and end_value
            amplitude = (end_value - start_value) / 2
            midpoint = (end_value + start_value) / 2
            cyclic_value = midpoint + amplitude * jnp.cos(angle)
            return jnp.where(is_delayed, start_value, cyclic_value)
        elif schedule == "sine":
            # Apply delay to cyclic schedules as well
            effective_step = jnp.maximum(step - delay_steps, 0.0)
            is_delayed = step < delay_steps
            angle = (
                2 * jnp.pi * effective_step
            ) / period - jnp.pi / 2  # Subtract π/2 to start at 0
            # Scale and shift to oscillate between start_value and end_value
            amplitude = (end_value - start_value) / 2
            midpoint = (end_value + start_value) / 2
            cyclic_value = midpoint + amplitude * jnp.sin(angle)
            return jnp.where(is_delayed, start_value, cyclic_value)
        else:
            raise ValueError(
                f"schedule must be either 'linear' 'cosine', or 'sine', not {schedule}"
            )

    return schedule_fn
