task:
env_overrides:
seed: 0
mimic:
  checkpoint: "260210_013247_285744"
  step: null
checkpoint_dir: highlvl_checkpoints
obs_keys:
  highlvl: task_obs
  policy: state
  value: state
logging:
  project: vnl-playground
  id: ""
ppo:
  num_timesteps: 3e8
  reward_scaling: 1.0
  episode_length: 1000
  normalize_observations: True
  action_repeat: 1
  unroll_length: 20
  num_minibatches: 16
  num_updates_per_batch: 4
  discounting: 0.99
  learning_rate: 1e-4
  entropy_cost: 0.01
  num_envs: 4096
  batch_size: 1024
  max_grad_norm: 1.0
  eval_every: 5e6
  network_factory:
    policy_hidden_layer_sizes: [1024, 512, 256]
    value_hidden_layer_sizes: [1024, 512, 256]
    distribution_type: normal
    state_dependent_std: true
    init_noise_std: 0.0
    noise_std_type: "log"