data_path:

run_config:
  agent_name: rodent
  run_name: imitation_debug
  seed: 0
  reward_scaling: 1
  normalize_observations: true
  action_repeat: 1
  unroll_length: 20

env_config:
  env_name: "multi clip"
  # walker 
  walker_name: rodent
  walker_xml_path: 
  ghost_xml_path: "environment/walker/assets/rodent_ghostpair_scale080.xml"
  torque_actuators: true
  num_resets_per_eval: 1

  # task
  task_name: imitation
  physics_steps_per_control_step: 5
  reward_weights:
    too_far_dist: 0.01
    bad_pose_dist: 20
    bad_quat_dist: 1
    ctrl_cost_weight: 0.02
    ctrl_diff_cost_weight: 0.02
    pos_reward_weight: 1.0
    quat_reward_weight: 1.0
    joint_reward_weight: 1.0
    angvel_reward_weight: 0.0
    bodypos_reward_weight: 0.0
    endeff_reward_weight: 1.0
    healthy_z_range: [0.0325, 0.5]
  
  # Mujoco config
  solver: "cg"
  iterations: 4
  ls_iterations: 4

network_config:
  arch_name: intention
  encoder_layer_sizes: [512, 512]
  decoder_layer_sizes: [512, 512]
  critic_layer_sizes: [512, 512]
  intention_size: 60
  kl_weight: 1e-4

train_config:
  num_envs: 2048
  num_timesteps: 10_000_000_000
  eval_every: 10_000_000
  batch_size: 512
  num_minibatches: 4
  num_updates_per_batch: 4
  learning_rate: 1e-4
  clipping_epsilon: 0.2
  episode_length: 200        
  discounting: 0.95        
  action_repeat: 1
  entropy_cost: 1e-2

logging_config:
  project_name: "vnl_debug"
  clip_id: -1
  model_path: "model_checkpoints"
  algo_name: "ppo"