walker_config:
  torque_actuators: False 
  xml_path: /root/vast/scott-yang/Brax-Rodent-Run/models/rodent.xml
  joint_names:
    - vertebra_1_extend
    - hip_L_supinate
    - hip_L_abduct
    - hip_L_extend
    - knee_L
    - ankle_L
    - toe_L
    - hip_R_supinate
    - hip_R_abduct
    - hip_R_extend
    - knee_R
    - ankle_R
    - toe_R
    - vertebra_C11_extend
    - vertebra_cervical_1_bend
    - vertebra_axis_twist
    - atlas
    - mandible
    - scapula_L_supinate
    - scapula_L_abduct
    - scapula_L_extend
    - shoulder_L
    - shoulder_sup_L
    - elbow_L
    - wrist_L
    - scapula_R_supinate
    - scapula_R_abduct
    - scapula_R_extend
    - shoulder_R
    - shoulder_sup_R
    - elbow_R
    - wrist_R
    - finger_R
  body_names:
    - torso
    - pelvis
    - upper_leg_L
    - lower_leg_L
    - foot_L
    - upper_leg_R
    - lower_leg_R
    - foot_R
    - skull
    - jaw
    - scapula_L
    - upper_arm_L
    - lower_arm_L
    - finger_L
    - scapula_R
    - upper_arm_R
    - lower_arm_R
    - finger_R
  end_eff_names:
    - foot_L
    - foot_R
    - hand_L
    - hand_R
    - skull